CREATE TABLE recipes (
	recipe_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id INTEGER REFERENCES users (user_id) NOT NULL,
	title TEXT NOT NULL,
	recipe_description TEXT,
	instructions TEXT NOT NULL
);